- name: Condition 3
  hosts: nodes
  tasks:
    - name: Date
      command: "date"
      when: ansible_os_family == "CentOS"
    # when: ansible_os_family == "Ubuntu"
      register: dateout
    - debug:
        var: dateout.stdout_lines

#ansible_distribution_major_version: "16"
#ansible_distribution_release: "xenial"
#ansible_distribution_version: "16.04"
#ansible_distribution_file_variety: "Debian"