- name: Change the hostname
  hosts: nodes1
  tasks:
    - name: Change hostname
      hostname:
        name: managed-node1
      register: changeHostname
    - name: Reboot
      reboot:
      when: changeHostname.changed
    - name: Command
      command: "ls /opt"
      when: changeHostname is skipped