- name: Install&enabled postfix service
  hosts: nodes
  gather_facts: false
  tasks:
    - name: Install postfix with yum
      yum:
        name: postfix*
        state: installed
    - name: Restart&enabled postfix
      service:
        name: postfix
        state: restarted
        enabled: yes
