- name: Create new users
  hosts: nodes1
  become_user: root
  become_method: sudo
  become: true
  tasks:
    - name: Create a new user Cigdem
      user:
        name: Cigdem
        state: present
    - name: Create a new user Alp
      user:
        name: Alp
        state: present
    - name: Create a new user Berk
      user:
        name: Berk
        state: present
