- name: Zip example 3
  hosts: nodes1
  tasks:
    - name: Zip file&directory
      archive:
        path:
          - /opt/ansible/ansible.txt
        dest: /tmp/file.tar.gz
        format: gz
        exclude_path:
          - /opt/ansible/ansible1.txt