- name: Install Jdk
  hosts: nodes
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Download Java
      command: wget -P /opt/java http://x.x.x.x/jdk-8u231-linux-x64.rpm
      environment:
        http_proxy
        https_proxy
    - name: Yum local install
      yum:
        name: /opt/java/jdk-8u231-linux-x64.rpm
        state: present
