- name: Debug message 9
  hosts: nodes
  tasks:
    - name: Execute 'df -h' command
      command: "df -h"
      register: dfout
    - debug:
        var: dfout.stdout_lines
    - name: Execute 'free -m' command
      register: freememout
      command: "free -m"
    - debug:
        var: freememout.stdout_lines
    - name: Execute 'date' command
      register: dateout
      command: "date"
    - debug:
        var: dateout.stdout_lines