- name: Install Docker-compose
  hosts: nodes
  become: true
  become_method: sudo
  become_user: root
  gather_facts: no
  vars:
    unames: Linux
    unamem: x86_64
    version: 1.29.2
  tasks:
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/{{ version }}/docker-compose-{{ unames }}-{{ unamem }}
        dest: /usr/local/bin/docker-compose
        mode: 755
